[[SanDiego]]
	date = '10/14/2022'
	temperature = '65.6'
	low = '63.2'
	high = '69.0'
	quality = 'Cloudy'
[[SanDiego]]
	date = '10/15/2022'
	temperature = '63.9'
	low = '62.5'
	high = '67.0'
	quality = 'Cloudy'
[[SanDiego]]
	date = '10/16/2022'
	temperature = '66.3'
	low = '62.3'
	high = '73.5'
	quality = 'Partially cloudy'
[[SanDiego]]
	date = '10/17/2022'
	temperature = '67.9'
	low = '65.6'
	high = '70.4'
	quality = 'Sunny'
[[SanDiego]]
	date = '10/18/2022'
	temperature = '71.3'
	low = '67.7'
	high = '74.6'
	quality = 'Partially cloudy'
[[SanDiego]]
	date = '10/19/2022'
	temperature = '78.1'
	low = '72.9'
	high = '87.9'
	quality = 'Cloudy'
[[SanDiego]]
	date = '10/20/2022'
	temperature = '71.0'
	low = '69.3'
	high = '72.6'
	quality = 'Partially cloudy'
[[SanDiego]]
	date = '10/21/2022'
	temperature = '68.6'
	low = '66.6'
	high = '70.4'
	quality = 'Sunny'
[[SanDiego]]
	date = '10/22/2022'
	temperature = '65.3'
	low = '63.6'
	high = '66.6'
	quality = 'Partially cloudy'
[[SanDiego]]
	date = '10/23/2022'
	temperature = '63.7'
	low = '63.1'
	high = '64.8'
	quality = 'Cloudy'
[[SanDiego]]
	date = '10/24/2022'
	temperature = '65.9'
	low = '63.7'
	high = '67.7'
	quality = 'Partially cloudy'
[[SanDiego]]
	date = '10/25/2022'
	temperature = '69.3'
	low = '65.6'
	high = '74.2'
	quality = 'Sunny'
[[SanDiego]]
	date = '10/26/2022'
	temperature = '69.0'
	low = '66.3'
	high = '72.6'
	quality = 'Partially cloudy'
[[SanDiego]]
	date = '10/27/2022'
	temperature = '66.9'
	low = '65.6'
	high = '69.0'
	quality = 'Sunny'
[[SanDiego]]
	date = '10/28/2022'
	temperature = '67.7'
	low = '65.4'
	high = '70.1'
	quality = 'Sunny'
[[SanDiego]]
	date = '10/29/2022'
	temperature = '70.6'
	low = '68.1'
	high = '73.8'
	quality = 'Sunny'
