[[SanDiego]]
[[10.21.2022]]
temperature = '67.6'
low = '64.5'
high = '72.9'
quality = 'Partially cloudy'
[[10.22.2022]]
temperature = '63.4'
low = '61.4'
high = '66.3'
quality = 'Stormy'
[[10.23.2022]]
temperature = '62.2'
low = '59.8'
high = '64.7'
quality = 'Raining'
[[10.24.2022]]
temperature = '67.0'
low = '63.2'
high = '70.2'
quality = 'Sunny'
[[10.25.2022]]
temperature = '67.2'
low = '65.4'
high = '70.1'
quality = 'Sunny'
[[10.26.2022]]
temperature = '66.1'
low = '64.5'
high = '68.3'
quality = 'Partially cloudy'
[[10.27.2022]]
temperature = '65.8'
low = '64.5'
high = '67.7'
quality = 'Partially cloudy'
[[10.28.2022]]
temperature = '66.1'
low = '64.5'
high = '68.4'
quality = 'Sunny'
[[10.29.2022]]
temperature = '65.1'
low = '63.9'
high = '66.3'
quality = 'Cloudy'
[[10.30.2022]]
temperature = '65.6'
low = '63.8'
high = '68.4'
quality = 'Cloudy'
[[10.31.2022]]
temperature = '67.3'
low = '65.0'
high = '69.9'
quality = 'Cloudy'
[[11.01.2022]]
temperature = '67.6'
low = '66.1'
high = '69.3'
quality = 'Partially cloudy'
[[11.02.2022]]
temperature = '66.1'
low = '64.7'
high = '67.7'
quality = 'Sunny'
[[11.03.2022]]
temperature = '66.7'
low = '64.7'
high = '69.2'
quality = 'Sunny'
[[11.04.2022]]
temperature = '67.2'
low = '65.4'
high = '69.5'
quality = 'Sunny'
[[11.05.2022]]
temperature = '65.6'
low = '64.7'
high = '67.2'
quality = 'Cloudy'
